Task 5
ozoncp/ocp-offer-api pull request #5
Opened 2021-08-08 13:45 UTC by evald24

# Задание V:

Нужно в пакете saver имплементировать `Saver` интерфейс, с возможностью писать в хранилище данные, через `Flusher`, сброс данных происходит во `flusher` по определенному таймауту или при вызове метода `Close`

```golang
package saver

type Saver interface {
	Save(entity models.Entity) // заменить на свою сущность
    // Init()
	Close()
}

// NewSaver возвращает Saver с поддержкой переодического сохранения
func NewSaver(
	capacity uint,
	flusher flusher.Flusher,
  // ...
) Saver {
  // ...
}
```

До сброса в хранилище, данные хранятся в **slice**. который принадлежит `saver`-у.

Установка capacity данного **slice**-a идет на этапе конструирование -  при вызове `NewSaver`

2021-08-10 16:19 UTC, slava-nikulin requested changes

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +	offers, _ := s.flusher.Flush(s.offers)
лучше понятнее назвать. unsavedOffers

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +			case <-s.notifier.Notify():
нотифаер не нужен. Используй просто тикер. Не усложняй

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +	s.wait.Wait()
Вэйтгруппы тут не нужны. Кончится горутина, вызовется дефёр с флашем

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +				s.offers = append(s.offers, offer)
надо задействовать капасити. Если превышен, то вызывать флаш. Либо пропускать ход

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +	s.offers = s.offers[:copy(s.offers, offers)]
Тут сложно. Давай пересоздавать слайс с нужной капасити и append делать. При этом следить, что капасити не превышен. Все лишние - в канал

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +	s.offers = s.offers[:copy(s.offers, offers)]
Либо просто пересоздай слайс, а несохраненные - обратно в канал

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +	s.offers = s.offers[:copy(s.offers, offers)]
s.offers[:0] вот так в смысле

2021-08-10 16:19 UTC, slava-nikulin commented on internal/saver/saver.go
> +func (s *saver) Init() error {
Если решил инит делать, то по идее нужно переоткрывать закрытые каналы. Либо упростить и сделать без Init

2021-08-10 17:57 UTC, evald24 commented on internal/saver/saver.go
> +	offers, _ := s.flusher.Flush(s.offers)
Сделал

2021-08-10 17:57 UTC, evald24 commented on internal/saver/saver.go
> +			case <-s.notifier.Notify():
Удалил

2021-08-10 18:37 UTC, evald24 commented on internal/saver/saver.go
> +	s.wait.Wait()
Убрал

2021-08-10 18:37 UTC, evald24 commented on internal/saver/saver.go
> +				s.offers = append(s.offers, offer)
Окей, слелал пропуск хода

2021-08-10 18:38 UTC, evald24 commented on internal/saver/saver.go
> +	s.offers = s.offers[:copy(s.offers, offers)]
Обнуляю и закидываю в него оставшиеся не сохранённые

2021-08-10 18:39 UTC, evald24 commented on internal/saver/saver.go
> +func (s *saver) Init() error {
Сделал открытие

2021-08-11 08:02 UTC, slava-nikulin requested changes

2021-08-11 08:02 UTC, slava-nikulin commented on internal/saver/saver.go
> +				// иначе пропускаем
тогда обратно в канал нужно положить. Я чуть по-другому бы сделал 
```
s.offers = append(s.offers, offer)
if uint(len(s.offers)) >= s.capacity {
s.flushOffers()
}
```

2021-08-11 08:21 UTC, evald24 commented on internal/saver/saver.go
> +				// иначе пропускаем
Сделал

2021-08-11 09:00 UTC, slava-nikulin approved these changes

2021-08-11 09:09 UTC, merged